### ISSUE TITLE
New check suggestion: `HaveLen(0)` should be `BeEmpty()`

### ISSUE THREAD

**Issue by oscr** [nunnatsa/ginkgolinter#46]
Hi,

When adding ginkgolinter len assertaion check to Cluster API I got a [really good comment](https://github.com/kubernetes-sigs/cluster-api/pull/8087#discussion_r1101916262) about changing `HaveLen(0)` to `BeEmpty()`. I would therefore like to suggest it as a new check for the linter.

Incorrect example.
<strike>
Original code:
`g.Expect(len(handlers)).To(Equal(0))`

Suggested code by gingkolinter:
`g.Expect(handlers).To(HaveLen(0))`

Suggested improvement: 
`g.Expect(handlers).To(BeEmpty())`
</strike>

Thanks for this great new linter @nunnatsa!

**Comment by nunnatsa** [comment]
Hi @oscr 

It's very cool you adopted this linter! Thanks for that. And thanks for this comment.

I wander: did you run the linter executable with the `-fix` parameter? or did you change it manually? What was the original warning from the linter?

I'm asking to understand if this is a bug, since the linter changes/suggest `Expect(len(x)).Should(Equal(0))` ==> `Expect(x).Should(BeEmpty())`.

If you manually changed to `HaveLen(0)`, then I guess I can add this check as well (`HaveLen(0)` ==> `BeEmpty()`)

**Comment by oscr** [comment]
Hi @nunnatsa! 

Thanks for the quick reply! Looking at it again I made a mistake in the issue description. ginkgolinter does suggest `BeEmpty()` so my example wasn't correct. Sorry for that. It seems like ginkgolinter doesn't pick up e g: `g.Expect(nsList.Items).Should(HaveLen(0))`.

**Comment by nunnatsa** [comment]
@oscr hi. Will you have some time to review #47 with the implementation of this issue?
